### ISSUE TITLE
Radical media (BOTS) ethics and practice

### ISSUE THREAD

**Issue by mj-saunders** [Openmedianetwork/OMN#1]
https://github.com/Openmedianetwork/OMN/wiki/Radical-media-(BOTS)-ethics-and-practice
In response:

> Q. what is a good way to AUTO add this good stuff to the wider #openweb

Are you asking for alternatives to RSS-to-Toot?

> Q. what can we avoid to have bad outcomes in this.

Any bot accounts would have to be human approved before being created?

> Q. The accounts should be free for the CC content owner to take over and run them selves if they like.

This means we would need an rss toot system that has a front-end and multiple users, right? This may be possible with https://github.com/blind-coder/rsstootalizer (shall check soon). I believe this may limit options unless we create custom solution.
Also, would this be unnecessary if the bot toots all RSS content? That way, at best perhaps we could simply mention the bot account has been "verified" by original feed owner.

> Q. How much content flow is to much

It depends how we are sourcing content. If we are pulling from RSS feeds, do we limit what is tooted by hashtag or keyword list? Who decides upon the list? Or just publish everything, unbiased from the feed?
If the bot account is connected only to one RSS feed, and only posts to followers, one could argue that enough is everything from the feed.

> Q. Pushing out linking to copyright content? Best practice on this.

Please can you give some examples before further discussion.

**Comment by Openmedianetwork** [comment]
The radical alt media in the uk are not very clear or knowledgeable about the #openweb and use the #closedweb #dotcons for their bulk distribution.

Like the verified by original owner :) the idea is that when they become interested/engaged they can take ownership of the account and then its no longer a BOT its them.

Think filtering would be difficult so its likely to be the whole of the RSS feed this might become a flood for popular sites such as https://www.thecanary.co we need to trial and error this :)

Some alt media has strait copyright rather than copyleft licenses. This is actually not a problem for posting links under fair use but the might be willful misunderstanding of this issue by a vocal minority.

**Comment by mj-saunders** [comment]
> the idea is that when they become interested/engaged they can take ownership of the account and then its no longer a BOT its them

Makes more sense now, that when they take over, the bot dies. I suppose prior to that, if they are happy with the rss bot, they can "verify" its' existence.

> ...this might become a flood for popular sites such as https://www.thecanary.co we need to trial and error this :)

Flood would be bad. Each bot would need to monitor how frequent the toots are. If they go over a certain limit we:
1. could "rate limit" - only display every nth RSS post. not ideal
2. could "rate limit: - toot a digest of n (maybe 5) posts at a time
3. Use a hashtag or keyword list - but who decides? And I guess the bot would have to somehow publish and be clear what tags it is searching for and posting.

> Some alt media has strait copyright rather than copyleft licenses

Surely, if we are only utilising RSS feeds there wouldn't be an issue...
Possible solution: set up bot, email rss originator, run bot until originator takes control or complains. If they complain, offer to kill bot, but mention how many followers they have garnered first (if significant)?

**Comment by Openmedianetwork** [comment]
I like both 1&2  as solutions to food problem, two is more elegant but one would work. 

Strait copyright is more a emotional issue than a legal one as you say we are just posting a link. Just have to tread carefully here.

**Comment by mj-saunders** [comment]
> I like both 1&2 as solutions to food problem, two is more elegant but one would work.

RSSTootalizer is able to filter by hashtag or leyword - we just have to figure the appropriate regular expression...so opetion 3 is still a potential.

1 and 2 both require building new functionality into RSSTootalizer - will have a deeper look when I get a chance

**Comment by mj-saunders** [comment]
a functioning bot (prototype?) is now running based on solution 2
